project:
  type: book
  output-dir: docs
  
book:
  title: "A simulation of bias introduced by missing confounder data"
  author: "Janick Weberpals"
    
  chapters:
    # landing page
    - index.qmd
        
    - part: Data generation background
      chapters:
        - scripts/01_data_generation.qmd
        - scripts/02_missingness_generation.qmd

    - part: Simulation
      chapters:
        - scripts/03_run_simulation.qmd

  reader-mode: true
  repo-url: https://gitlab-scm.partners.org/drugepi/bias_simulation_missing_data
  site-url: https://drugepi.gitlab-pages.partners.org/bias_simulation_missing_data
  repo-actions: [issue]

format:
  html:
    code-fold: true
    code-summary: "Show the code"
    theme: cosmo
    engine: knitr
    page-layout: full
    link-external-icon: true
    link-external-newwindow: true

